branches:
  only:
  - master
  - "/^v.*$/"
language: cpp
matrix:
  include:
  - name: Linux x86_64
    dist: bionic
    script:
    - make -f Makefile.libretro -j 4
    - zip genesis_plus_gx-Linux-x86_64-${TRAVIS_TAG:1}.zip genesis_plus_gx_libretro.so
  - name: Linux arm64
    dist: bionic
    arch: arm64
    before_install:
    - sudo apt-get install zip
    script:
    - make -f Makefile.libretro -j 4
    - zip genesis_plus_gx-Linux-arm64-${TRAVIS_TAG:1}.zip genesis_plus_gx_libretro.so
  - name: Linux armv7 neon
    dist: bionic
    services:
    - docker
    before_install:
    - sudo apt-get install zip
    script:
    - docker pull dockcross/linux-armv7
    - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp dockcross/linux-armv7
      make platform=unix-armv-neon-hardfloat -f Makefile.libretro -j 4
    - zip genesis_plus_gx-Linux-arm-${TRAVIS_TAG:1}.zip genesis_plus_gx_libretro.so
  - name: OSX x86_64
    os: osx
    osx_image: xcode11.3
    script:
    - make platform=osx -f Makefile.libretro -j 4
    - zip genesis_plus_gx-OSX-x86_64-${TRAVIS_TAG:1}.zip genesis_plus_gx_libretro.dylib
  - name: Windows x86_64
    os: windows
    before_install:
    - choco install make --ignore-checksums
    script:
    - make platform=win -f Makefile.libretro -j 4
    - 7z a genesis_plus_gx-Windows-x86_64-${TRAVIS_TAG:1}.zip genesis_plus_gx_libretro.dll
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fGdCCzuc+QAZiO+0D6fKLoeqaZfGBb81oU9ybXxwcKrlDhqWoujjW02yf5uNmk5HZA2OGq9Xxv7JQBoCDeKLQh6FGQuPMJSwl2OIKdMBZ4WLetHndJipOaetyEyx6WLPydFUR8lwtWx4medJ0s8AQGK3T+qCphPMDRmty2xZMqgOb/TXn7T8inBUpwPnHxnwsGB7j8Qsy7oPTxaIIZNnzmRRLssYzT+7v4BFqICLV8OTQ2ldEXIDckMYXBg87oCaGBoxsUj1aC2vjAHq2oCR1SUKUdMUv5Xk8AfOViwhzW/L4veRUvOdhLXc2JxEWFSRJ/2SJ5bAkdk4f5Xd3G5qE9J0zxtnPzlRUSuAVOVVojtFAq3WPNd+lq8cMdQJeH3x6WYuDJEhRTmZtpsFf3EvK+sPeCXSSBbQYOfDhCHqdB45t4Ujlxr3UmlDQiPhR7tOSKhltwq3eaNjRBKKFwSq1pgKvU+FNTY9NIgxIsXcps4ZOWpVfqb227CDqDmgs7RZejsgHEHXkA5ytlD4Q0+ZobF8WAlV/tWzgcxRApUsoJgwM5yuKx/l6w3uSe8IUe00jGSWpMb06MFaR5jTuO73VxXQcPRwsT4TAQoaIWpsXbR6kXPVphiDhy0bTO7QLpmH0Tc+1U0KFr0o8FBq6UH+a6jpfybVFS1w2Mg4vxr7GG4=
  file:
  - genesis_plus_gx-Linux-x86_64-${TRAVIS_TAG:1}.zip
  - genesis_plus_gx-Linux-arm64-${TRAVIS_TAG:1}.zip
  - genesis_plus_gx-Linux-arm-${TRAVIS_TAG:1}.zip
  - genesis_plus_gx-OSX-x86_64-${TRAVIS_TAG:1}.zip
  - genesis_plus_gx-Windows-x86_64-${TRAVIS_TAG:1}.zip
  on:
    repo: piepacker/genesis_plus_gx
    tags: true

